- name: Upload File to Terraform Bucket
  hosts: localhost
  connection: local
  tasks:
    - name: Get Bucket Name from Env
      set_fact:
        target_bucket: "{{ lookup('env', 'CREATED_S3_BUCKET_NAME') }}"

    - name: Debug - Show the bucket name
      debug:
        msg: "The bucket name being used is: '{{ target_bucket }}'"

    - name: Fail if bucket name is empty
      fail:
        msg: "The bucket name is empty! Please check Spacelift Dependencies mapping."
      when: target_bucket | length < 3

    - name: Create a local dummy file
      copy:
        content: "Hello! This was uploaded via Ansible to a bucket named {{ target_bucket }}"
        dest: "/tmp/spacelift_report.txt"

    - name: Upload file to S3
      amazon.aws.s3_object:
        bucket: "{{ target_bucket }}"
        object: "uploads/ansible_file.txt"
        src: "/tmp/spacelift_report.txt"
        mode: put
        region: "us-west-2"
